spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:~/testdb
    username: sa
    password:
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 1
      pool-name: MyHikariCP
      register-mbeans: true
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
